# originally from the project https://github.com/wurstmeister/kafka-docker and https://hub.docker.com/r/wurstmeister/kafka
# docker-compose -f docker-compose-all-services.yml up
version: '2'
services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    build:
#      context: ./kafka
#      dockerfile: Dockerfile
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.81
#      KAFKA_CREATE_TOPICS: "test:1:1"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    image: generalmeow/bigly-producer:latest
    environment:
      BOOTSTRAP_SERVER: 192.168.1.81
      BOOTSTRAP_SERVER_PORT: 9092
  outputter:
    image: generalmeow/bigly-outputter:latest
    environment:
      BOOTSTRAP_SERVER: 192.168.1.81
      BOOTSTRAP_SERVER_PORT: 9092