repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx


releases:
  - name: ingress
#    namespace: local
    chart: ingress-nginx/ingress-nginx
    version: 4.2.5
    values:
      - ingress/values.yaml
    labels:
      app: ingress-nginx
    installed: true

helmDefaults:
  kubeContext: microk8s
  wait: true
  timeout: 500