cp-zookeeper:
  servers: 1
  persistence:
    dataDirSize: 10Gi
  prometheus:
    jmx:
      enabled: false

cp-kafka:
  brokers: 1
  configurationOverrides:
    "offsets.topic.replication.factor": "1"
    "confluent.metrics.reporter.topic.replicas": "1"
    "advertised.listeners": |-
      EXTERNAL://127.0.0.1:31090
  persistence:
    size: 5Gi
  prometheus:
    jmx:
      enabled: false
  nodeport:
    enabled: true

cp-schema-registry:
  prometheus:
    jmx:
      enabled: false

cp-kafka-rest:
  enabled: false

cp-kafka-connect:
  configurationOverrides:
    "config.storage.replication.factor": "1"
    "offset.storage.replication.factor": "1"
    "status.storage.replication.factor": "1"
  prometheus:
    jmx:
      enabled: false

cp-ksql-server:
  enabled: false

cp-control-center:
  enabled: true
  configurationOverrides:
    "replication.factor": "1"